(import Utils      "utils.scm")
(import Calendar   "calendar.scm")
(import TLS        "tls.scm")
(import List       "std.list.scm")
(import MOB        "man_or_boy.scm")
(import Fac        "factorial.scm")
(import Sort       "sort.scm")
(import Quine      "quine.scm")
(import Quasiquote "quasiquote.scm")
(import TLS_Intp   "interpreter.scm")
(import Calculator "calculator.scm")
(import Generator  "generator.scm")
(import FFT        "fft.scm")
(import BigInt     "big_int.scm")
(import Shudu      "shudu.scm")

;; 内存占用比较小的测试用例
(Calendar.run)
(TLS.run)
(List.run)
(MOB.run)
(Fac.run)
(Sort.run)
(Quine.run)
(Quasiquote.run)
(TLS_Intp.run)
(Calculator.run)
(Generator.run)
(FFT.run)
(BigInt.run)
(Shudu.run)
