(native Math)
(native System)
(native String)

(import BigInt "big_int.scm")
(import BF "brainfuck.scm")
(import Calculator "calculator.scm")
(import Calendar "calendar.scm")
(import CAS "cas.scm")
(import Church "church_encoding.scm")
(import Coroutine "coroutine.scm")
(import Fac "factorial.scm")
(import FFT "fft.scm")
(import Generator "generator.scm")
(import Interpreter "interpreter.scm")
(import List "list.scm")
(import MoB "man_or_boy.scm")
(import Quasiquote "quasiquote.scm")
(import Quickqort "quicksort.scm")
(import Quine "quine.scm")
(import Shudu "shudu.scm")
(import TheLittleSchemer "tls.scm")
;; 异步的
(import Sleepsort "sleepsort.scm")


(define memstat
  (lambda ()
    (define mem (System.memstat))
    (define vm_cap (get_item mem 0))
    (define vm_use (get_item mem 1))
    (define heap_cap (get_item mem 2))
    (define heap_use (get_item mem 3))
    (display "============ 内存统计 ============\n")
    (display "  总内存：") (display (/ (/ (+ vm_cap heap_cap) 1024) 1024)) (display "MiB") (newline)
    (display "    工作区容量：") (display vm_cap) (display "B") (newline)
    (display "    工作区已用：") (display (* 100 (/ vm_use vm_cap))) (display "%") (newline)
    (display "    用户区容量：") (display heap_cap) (display "B") (newline)
    (display "    用户区已用：") (display (* 100 (/ heap_use heap_cap))) (display "%") (newline)
    (display "=================================\n")))

(memstat)

(display "======================== Animac 测试用例 ========================\n")
(BigInt.run)
(display "======================== Animac 测试用例 ========================\n")
(BF.run)
(display "======================== Animac 测试用例 ========================\n")
(Calculator.run)
(display "======================== Animac 测试用例 ========================\n")
(Calendar.run)
(display "======================== Animac 测试用例 ========================\n")
(CAS.run)
(display "======================== Animac 测试用例 ========================\n")
(Church.run)
(display "======================== Animac 测试用例 ========================\n")
(Coroutine.run)
(display "======================== Animac 测试用例 ========================\n")
(Fac.run)
(display "======================== Animac 测试用例 ========================\n")
(FFT.run)
(display "======================== Animac 测试用例 ========================\n")
(Generator.run)
(display "======================== Animac 测试用例 ========================\n")
(Interpreter.run)
(display "======================== Animac 测试用例 ========================\n")
(List.run)
(display "======================== Animac 测试用例 ========================\n")
(MoB.run)
(display "======================== Animac 测试用例 ========================\n")
(Quasiquote.run)
(display "======================== Animac 测试用例 ========================\n")
(Quickqort.run)
(display "======================== Animac 测试用例 ========================\n")
(Quine.run)
(display "======================== Animac 测试用例 ========================\n")
(Shudu.run)
(display "======================== Animac 测试用例 ========================\n")
(TheLittleSchemer.run)
(display "======================== Animac 测试用例 ========================\n")
(Sleepsort.run)

(System.set_timeout 1200 (lambda () (memstat) ))

